#ifndef USB_DESCRIPTORS_H_
#define USB_DESCRIPTORS_H_

enum
{
  REPORT_ID_KEYBOARD = 1,
  REPORT_ID_MOUSE = 2,
  REPORT_ID_CONSUMER_CONTROL,
  REPORT_ID_GAMEPAD = 3,
  REPORT_ID_COUNT
};

#endif /* USB_DESCRIPTORS_H_ */